version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "`🤖 Dependabot:` "
    ignore:
      - dependency-name: "nodemon"
